apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/your-org/platform-templates/k8s/base?ref=v1.0.0

nameSuffix: ""
images:
  - name: placeholder-image
    newName: swr.af-south-1.myhuaweicloud.com/your-org/svc-orders
    newTag: latest   # overwritten by CI/CD or ArgoCD image updater

patches:
  - target:
      kind: Deployment
      name: placeholder-service
    patch: |-
      - op: replace
        path: /metadata/name
        value: svc-orders
      - op: replace
        path: /spec/selector/matchLabels/app
        value: svc-orders
      - op: replace
        path: /spec/template/metadata/labels/app
        value: svc-orders
  - target:
      kind: Service
      name: placeholder-service
    patch: |-
      - op: replace
        path: /metadata/name
        value: svc-orders
      - op: replace
        path: /spec/selector/app
        value: svc-orders
