name: ci

on:
  push:
    branches: [main]

jobs:
  build:
    uses: lemrex/platform/.github/workflows/reusable-build.yml@main
    with:
      service_name: test-orders
      language: node
    secrets:
      SWR_USERNAME: ${{ secrets.SWR_USERNAME }}
      SWR_PASSWORD: ${{ secrets.SWR_PASSWORD }}



      